language: python
python:
  - "3.6"
  - "3.7"
branches:
  only:
    - master
    - dev
matrix:
  include:
    # Test javascript as part of python3.4 tests
    - language: node_js
      node_js: node
      install:
        # Dependencies for PhantomJS used for qunit unit testing, these might already be there on travis-ci
        #- apt-get install libfontconfig1 fontconfig libfontconfig1-dev libfreetype6-dev
        # Setup grunt and the tests
        - npm install -g grunt-cli
        - npm install
      script:
        - grunt
# command to install dependencies
install:
  # Runtime requirements
  - pip install -r requirements.txt
  # Test requirements
  - pip install -r test-requirements.txt
script:
  # Python validations
  - find . -name \*.py -exec pycodestyle {} +
  # Ignoring missing docstrings for now
  # - find . -name \*.py -exec pep257 {} +
  - pylint opsy
